#' Do when
#'
#' Do something when something else is true
#'
#' @param .d An expression to do upon a condition being met.
#' @param .w A condition when \code{.d} should be done.
#' @param .s Time in seconds to wait between checking for file existence.
#'   The default is to wait 60 seconds between checking for a file.
#' @return Output as generated by \code{.d}
#' @export
do_when <- function(.d, .w, .s) {
  do_when_(rlang::enquo(.d), rlang::enquo(.w), .s)
}



do_when_ <- function(.d, .w, .s) {
  if (!rlang::is_quosure(.d))
    .d <- rlang::enquo(.d)
  if (!rlang::is_quosure(.w))
    .w <- rlang::enquo(.w)

  ## validate inputs
  stopifnot(
    rlang::is_quosure(.d),
    rlang::is_quosure(.w),
    is.numeric(.s)
  )

  ## format sleep message
  if (.s > 60) {
    wait_time <- paste0("about ", .s %/% 60, " minutes")
  } else {
    wait_time <- paste0(.s, " seconds")
  }

  ## while loop, broken by
  ##    - .w returning `TRUE`
  ##    - user interrupt
  while (TRUE) {
    ## if condition returns FALSE, then sleep
    if (!rlang::eval_tidy(.w)) {
      ## sleep message
      tfse::print_start("Waiting ", wait_time)
      ## sleep with interrupt condition
      zzz <- tryCatch(
        Sys.sleep(.s),
        interrupt = function(i) {
          tfse::print_complete("Interrupted!")
          return(FALSE)
        }
      )
      if (!is.null(zzz)) {
        x <- NULL
        break
      }
      next
    }
    tfse::print_complete("It's time!")
    x <- rlang::eval_tidy(.d)
    break
  }
  x
}
